global:
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#pavel_semyannikov'
