version: '3.3'

services:
  mongo_db:
    image: mongo:${MONGO_VERSION}
    volumes:
      - post_db:${MONGO_DB_DIR}
    networks:
      back_net:
        aliases:
          - post_db
          - comment_db

  ui:
    image: ${DOCKERHUB_USERNAME}/ui:${BUILD_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    ports:
      - ${PUMA_PORT}:${PUMA_PORT}/tcp
    networks:
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui

  post:
    image: ${DOCKERHUB_USERNAME}/post:${BUILD_VERSION}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      - back_net
      - front_net
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post

  comment:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    image: ${DOCKERHUB_USERNAME}/comment:${BUILD_VERSION}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
